# Generated by Django 3.1.2 on 2020-10-18 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Codigo_FallGuys',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=500),
        ),
    ]
