# Generated by Django 3.1.2 on 2020-10-18 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ForoApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='codigofg',
        ),
    ]
