# Generated by Django 3.1.2 on 2020-11-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForoApp', '0002_noticia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trucos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapa', models.CharField(max_length=60)),
                ('imagen_truco', models.ImageField(null=True, upload_to='Trucos')),
                ('desc_truco', models.CharField(max_length=600)),
            ],
        ),
    ]
