# Generated by Django 3.1.2 on 2020-10-18 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ForoApp', '0002_auto_20201018_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Codigo_FallGuys',
            new_name='Código_FallGuys',
        ),
    ]
