# Generated by Django 3.1.2 on 2020-11-06 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForoApp', '0004_mostrarusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='desc',
            field=models.CharField(max_length=6000),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(max_length=500),
        ),
    ]
